// CEI RSS Function v4.2
// Real RSS/XML fetch + article-aware Cedarbrook intelligence. No npm dependencies required.
const SOURCES = [
  { name: "Bank of Canada", category: "Rates", tier: "Tier 1", relevance: 5, feedUrl: "https://www.bankofcanada.ca/feed/", fallbackUrl: "https://www.bankofcanada.ca/rss-feeds/" },
  { name: "CMHC", category: "Housing", tier: "Tier 1", relevance: 5, feedUrl: "https://www.cmhc-schl.gc.ca/media-newsroom/cmhc-news-room-rss", fallbackUrl: "https://www.cmhc-schl.gc.ca/media-newsroom/cmhc-news-room-rss" }
];

const TERMS = {
  local: ["chilliwack", "fraser valley", "abbotsford", "mission", "langley", "hope", "lower mainland", "british columbia", "b.c.", "bc"],
  cedarbrook: ["land", "development", "subdivision", "servicing", "infrastructure", "retail", "commercial", "industrial", "multifamily", "multi-family", "rental", "housing", "starts", "absorption", "population", "affordability", "mortgage", "interest rate", "rate", "inflation", "construction", "supply", "employment", "municipal", "approval", "permit", "zoning", "transportation", "townhome", "apartment"],
  rates: ["rate", "rates", "interest", "mortgage", "monetary", "inflation", "bond", "credit", "borrowing", "lending"],
  housing: ["housing", "home", "homes", "starts", "rental", "rent", "affordability", "supply", "inventory", "apartment", "multifamily", "multi-family", "townhome"],
  construction: ["construction", "building", "materials", "labour", "labor", "supply chain", "cost", "costs", "permit", "permits"],
  retail: ["retail", "consumer", "spending", "business", "commercial", "store", "restaurant", "employment", "population"],
  approvals: ["municipal", "approval", "approvals", "zoning", "permit", "permits", "infrastructure", "servicing", "transportation", "water", "sewer", "road"]
};

function decodeEntities(text = "") {
  return text.replace(/<!\[CDATA\[(.*?)\]\]>/gs, "$1").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#039;/g, "'").replace(/&#8217;/g, "'").replace(/&#8211;/g, "-").replace(/&#8212;/g, "-").replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();
}
function getTag(block, tagName) { const m = block.match(new RegExp(`<${tagName}[^>]*>([\\s\\S]*?)<\\/${tagName}>`, "i")); return m ? decodeEntities(m[1]) : ""; }
function getAtomLink(block) { const m = block.match(/<link[^>]+href=["']([^"']+)["'][^>]*>/i); return m ? m[1].trim() : ""; }
function normalizeDate(value) { if (!value) return null; const d = new Date(value); return Number.isNaN(d.getTime()) ? null : d.toISOString(); }
function textOf(a) { return `${a.source || ""} ${a.category || ""} ${a.title || ""} ${a.summary || ""}`.toLowerCase(); }
function has(text, list) { return list.some(x => text.includes(x)); }
function count(text, list) { return list.reduce((n, x) => n + (text.includes(x) ? 1 : 0), 0); }
function inferCategory(a) { const t = textOf(a); const s = { Rates: count(t, TERMS.rates), Housing: count(t, TERMS.housing), Construction: count(t, TERMS.construction), Retail: count(t, TERMS.retail), Municipal: count(t, TERMS.approvals) }; const best = Object.entries(s).sort((x, y) => y[1] - x[1])[0]; return best && best[1] > 0 ? best[0] : (a.category || "General"); }
function isChilliwackRelevant(a) { const t = textOf(a); return has(t, TERMS.local) || has(t, TERMS.cedarbrook); }
function isFraserValleyRelevant(a) { return has(textOf(a), ["fraser valley", "chilliwack", "abbotsford", "mission", "hope", "langley", "lower mainland", "british columbia", "b.c.", "bc"]); }
function relevanceLevel(score) { return score >= 80 ? "High" : score >= 60 ? "Medium" : score >= 40 ? "Watch" : "Low"; }
function starsFromScore(score) { return score >= 90 ? 5 : score >= 75 ? 4 : score >= 60 ? 3 : score >= 40 ? 2 : 1; }
function scoreArticle(a) { const t = textOf(a); let s = 30; if (a.tier === "Tier 1") s += 10; if (has(t, TERMS.local)) s += 25; if (has(t, TERMS.cedarbrook)) s += 20; if (has(t, TERMS.rates)) s += 12; if (has(t, TERMS.housing)) s += 12; if (has(t, TERMS.construction)) s += 9; if (has(t, TERMS.retail)) s += 8; if (has(t, TERMS.approvals)) s += 8; const title = (a.title || "").toLowerCase(); if (has(title, TERMS.local)) s += 10; if (has(title, TERMS.cedarbrook)) s += 10; return Math.max(0, Math.min(100, s)); }
function inferImpact(a) { const t = textOf(a); if (has(t, ["decline", "declines", "fall", "falls", "drop", "drops", "slow", "slows", "weak", "recession", "higher rates"])) return "Bearish"; if (has(t, ["grow", "growth", "increase", "increases", "rise", "rises", "lower rates", "rate cut", "cuts", "improve", "strong", "demand"])) return "Bullish"; return "Neutral"; }
function inferWhy(article) { const t = textOf(article); const local = isFraserValleyRelevant(article); if (has(t, TERMS.rates)) return local ? "Rate and credit conditions may directly affect Cedarbrook buyer qualification, financing costs, absorption pace, and land underwriting in the Fraser Valley." : "Rate and credit conditions may affect Cedarbrook through borrowing costs, mortgage qualification, buyer confidence, and return expectations for land development."; if (has(t, TERMS.housing)) return local ? "Housing supply, rental, affordability, or starts data may shift the read on Chilliwack demand, competitive inventory, and Cedarbrook absorption assumptions." : "Housing market movement may affect Cedarbrook feasibility assumptions, future inventory risk, rental demand, and the timing of residential releases."; if (has(t, TERMS.construction)) return "Construction cost, labour, supply, or permit signals may affect Cedarbrook delivery timing, contingencies, servicing assumptions, and pro forma risk."; if (has(t, TERMS.retail)) return "Retail, consumer, employment, or business signals may affect Cedarbrook commercial demand, tenant interest, traffic assumptions, and phasing strategy."; if (has(t, TERMS.approvals)) return "Municipal, infrastructure, servicing, or approval signals may affect Cedarbrook entitlement risk, schedule confidence, and coordination with public agencies."; return "Potential economic signal to review for Cedarbrook land development, Chilliwack growth, absorption, retail demand, or approval risk."; }
function predictionHint(a) { const t = textOf(a); if (has(t, TERMS.rates)) return "If rate conditions ease or buyer confidence improves, Cedarbrook absorption and financing assumptions may strengthen over the next two quarters."; if (has(t, TERMS.housing)) return "If housing demand remains resilient while new supply is constrained, Cedarbrook residential release timing and absorption assumptions may improve."; if (has(t, TERMS.construction)) return "If construction cost or labour pressure increases, Cedarbrook contingency planning and delivery schedules may need closer monitoring."; if (has(t, TERMS.retail)) return "If consumer demand and local growth remain positive, Cedarbrook retail positioning may become stronger for tenant attraction conversations."; if (has(t, TERMS.approvals)) return "If approval or infrastructure constraints tighten, Cedarbrook schedule risk may increase and should be reviewed against current phasing assumptions."; return "Track whether this signal becomes confirmed by follow-up data before using it to adjust Cedarbrook assumptions."; }
function enrichArticle(a) { const category = inferCategory(a); const article = { ...a, category }; const relevanceScore = scoreArticle(article); const cedarbrookImpact = inferWhy(article); return { ...article, relevanceScore, relevanceLevel: relevanceLevel(relevanceScore), relevance: starsFromScore(relevanceScore), highRelevance: relevanceScore >= 80, chilliwackRelevant: isChilliwackRelevant(article), fraserValleyRelevant: isFraserValleyRelevant(article), impact: a.impact && a.impact !== "Unclassified" ? a.impact : inferImpact(article), cedarbrookImpact, why: cedarbrookImpact, signalType: category, predictionHint: predictionHint(article) }; }
function parseFeed(xml, source) { const blocks = xml.match(/<item[\s\S]*?<\/item>/gi) || xml.match(/<entry[\s\S]*?<\/entry>/gi) || []; return blocks.slice(0, 12).map(block => { const isAtom = /^<entry/i.test(block.trim()); const title = getTag(block, "title"); if (!title) return null; const link = isAtom ? (getAtomLink(block) || getTag(block, "link")) : getTag(block, "link"); const publishedRaw = getTag(block, "pubDate") || getTag(block, "published") || getTag(block, "updated"); const summary = getTag(block, "description") || getTag(block, "summary") || getTag(block, "content:encoded"); return enrichArticle({ id: `${source.name}-${title}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 120), title, source: source.name, category: source.category, tier: source.tier, relevance: source.relevance, impact: "Unclassified", link: link || source.fallbackUrl, url: link || source.fallbackUrl, published: normalizeDate(publishedRaw), summary, feedUrl: source.feedUrl }); }).filter(Boolean); }
async function fetchSource(source) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 9000); try { const response = await fetch(source.feedUrl, { signal: controller.signal, headers: { "User-Agent": "CEI-News-Aggregator/4.2 (+Netlify Function)", "Accept": "application/rss+xml, application/atom+xml, application/xml, text/xml, */*" } }); clearTimeout(timeout); if (!response.ok) return { source: source.name, ok: false, status: response.status, error: `HTTP ${response.status}`, articles: [] }; const text = await response.text(); if (!/<rss|<feed|<item|<entry/i.test(text)) return { source: source.name, ok: false, status: response.status, error: "Response did not look like RSS/Atom XML. Check feedUrl.", articles: [] }; const articles = parseFeed(text, source); return { source: source.name, ok: true, status: response.status, count: articles.length, articles }; } catch (error) { clearTimeout(timeout); return { source: source.name, ok: false, status: 0, error: error.name === "AbortError" ? "Request timed out" : error.message, articles: [] }; } }
exports.handler = async (event) => { if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET, OPTIONS", "Access-Control-Allow-Headers": "Content-Type" }, body: "" }; const results = await Promise.all(SOURCES.map(fetchSource)); const sources = results.map(({ source, ok, status, error, count }) => ({ source, ok, status, error, count: count || 0 })); const byId = new Map(); results.forEach(r => r.articles.forEach(a => { if (!byId.has(a.id)) byId.set(a.id, a); })); const articles = Array.from(byId.values()).sort((a, b) => (b.published ? new Date(b.published).getTime() : 0) - (a.published ? new Date(a.published).getTime() : 0)).slice(0, 30); return { statusCode: 200, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "public, max-age=900", "Access-Control-Allow-Origin": "*" }, body: JSON.stringify({ generatedAt: new Date().toISOString(), sources, articles }) }; };
